name: revolucao3d_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  youtube_player_flutter: ^8.1.2
  video_player: ^2.6.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  equatable: ^2.0.5
  cloud_firestore: ^4.8.1
  flutter_modular: ^5.0.3
  intl: ^0.18.0
  google_fonts: ^5.1.0
  collection: ^1.17.1
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  asuka: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
